spring.application.name=hemolink-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/HemoLink
spring.datasource.username=postgres
spring.datasource.password=admin
server.port=8082
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

jwt.secret=hemolink_ultra_secret_key_change_in_production_12345678901234567890
jwt.expiration=86400000
